#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-multi_json
Version  : 1.11.2
Release  : 6
URL      : https://rubygems.org/downloads/multi_json-1.11.2.gem
Source0  : https://rubygems.org/downloads/multi_json-1.11.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# MultiJSON
[![Gem Version](http://img.shields.io/gem/v/multi_json.svg)][gem]
[![Build Status](http://travis-ci.org/intridea/multi_json.svg)][travis]
[![Dependency Status](http://img.shields.io/gemnasium/intridea/multi_json.svg)][gemnasium]
[![Code Climate](http://img.shields.io/codeclimate/github/intridea/multi_json.svg)][codeclimate]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n multi_json-1.11.2
gem spec %{SOURCE0} -l --ruby > rubygem-multi_json.gemspec

%build
gem build rubygem-multi_json.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
multi_json-1.11.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/multi_json-1.11.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapter/blank%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapter/cdesc-Adapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapter/defaults-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapter/dump-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapter/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/AdapterError/build-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/AdapterError/cause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/AdapterError/cdesc-AdapterError.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Gson/cdesc-Gson.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Gson/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Gson/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/JrJackson/cdesc-JrJackson.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/JrJackson/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/JsonCommon/cdesc-JsonCommon.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/JsonCommon/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/JsonCommon/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/JsonGem/cdesc-JsonGem.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/JsonPure/cdesc-JsonPure.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Nsjsonserialization/cdesc-Nsjsonserialization.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Nsjsonserialization/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Nsjsonserialization/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Oj/cdesc-Oj.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Oj/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Oj/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/OkJson/cdesc-OkJson.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/OkJson/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/OkJson/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Yajl/cdesc-Yajl.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Yajl/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/Yajl/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Adapters/cdesc-Adapters.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/ConvertibleHashKeys/cdesc-ConvertibleHashKeys.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/ConvertibleHashKeys/prepare_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/ConvertibleHashKeys/stringify_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/ConvertibleHashKeys/symbolize_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/Utf8Error/cdesc-Utf8Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/abbrev-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/arrenc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/arrparse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/cdesc-OkJson.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/decode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/eat-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/encode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/falsetok-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/hexdec4-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/keyenc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/lex-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/nibble-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/nulltok-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/numenc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/numtok-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/objenc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/objparse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/pairparse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/rubydoesenc%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/strenc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/strtok-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/subst-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/surrogate%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/textparse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/tok-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/truetok-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/ucharcopy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/ucharenc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/unquote-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/valenc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/OkJson/valparse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Options/cdesc-Options.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Options/default_dump_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Options/default_load_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Options/dump_options%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Options/dump_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Options/get_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Options/load_options%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Options/load_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/ParseError/build-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/ParseError/cause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/ParseError/cdesc-ParseError.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/ParseError/data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Version/cdesc-Version.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/Version/to_s-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/adapter%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/cdesc-MultiJson.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/current_adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/decode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/default_adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/default_engine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/default_options%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/default_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/encode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/engine%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/engine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/load_adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/load_adapter_from_string_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/use-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/with_adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/MultiJson/with_engine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/multi_json-1.11.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/LICENSE.md
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapter_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/gson.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/jr_jackson.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_gem.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_pure.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/nsjsonserialization.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/oj.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/ok_json.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/adapters/yajl.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/convertible_hash_keys.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/options.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/parse_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/vendor/okjson.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib/multi_json/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/multi_json-1.11.2/multi_json.gemspec
/usr/lib64/ruby/gems/2.2.0/specifications/multi_json-1.11.2.gemspec
