#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-multi_json
Version  : 1.11.2
Release  : 7
URL      : https://rubygems.org/downloads/multi_json-1.11.2.gem
Source0  : https://rubygems.org/downloads/multi_json-1.11.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# MultiJSON
[![Gem Version](http://img.shields.io/gem/v/multi_json.svg)][gem]
[![Build Status](http://travis-ci.org/intridea/multi_json.svg)][travis]
[![Dependency Status](http://img.shields.io/gemnasium/intridea/multi_json.svg)][gemnasium]
[![Code Climate](http://img.shields.io/codeclimate/github/intridea/multi_json.svg)][codeclimate]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n multi_json-1.11.2
gem spec %{SOURCE0} -l --ruby > rubygem-multi_json.gemspec

%build
gem build rubygem-multi_json.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
multi_json-1.11.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/multi_json-1.11.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/LICENSE.md
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapter_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapters/gson.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapters/jr_jackson.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_gem.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_pure.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapters/nsjsonserialization.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapters/oj.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapters/ok_json.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/adapters/yajl.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/convertible_hash_keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/parse_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/vendor/okjson.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/lib/multi_json/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/multi_json-1.11.2/multi_json.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/multi_json-1.11.2.gemspec
